version: '3.7'

services:
  db:
    image: postgres:14.2-alpine3.15
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - patdet:/var/lib/postgresql/data
      - ./src/main/kotlin/com/sortinghat/pattern_detector/db/seed.sql:/seed.sql

volumes:
  patdet: