version: '3.8'

services:
  web:
    build: .
    env_file:
      - ./.env.docker-compose
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    env_file:
      - ./.env.docker-compose
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
